sd

diff --git a/.github/workflows/cypress-lambdatest.yml b/.github/workflows/cypress-lambdatest.yml
--- a/.github/workflows/cypress-lambdatest.yml
+++ b/.github/workflows/cypress-lambdatest.yml
@@ -34,9 +34,9 @@ jobs:
       - name: Execute lambdatest cli
         run: |
           if npm run ci:lambdatest --build_name=${{ github.head_ref }}-${{ github.run_id }}; then
-              echo "command succeeded"
+              echo "command succeeded"-$?
           else
-              echo "command failed"
+              echo "command failed"-$?
           fi
         env:
           LT_USERNAME: ${{secrets.LT_USERNAME}}
