sdd

diff --git a/.github/workflows/cypress-lambdatest.yml b/.github/workflows/cypress-lambdatest.yml
--- a/.github/workflows/cypress-lambdatest.yml
+++ b/.github/workflows/cypress-lambdatest.yml
@@ -1,5 +1,5 @@
 name: Lambdatest cypress integration
-on: workflow_dispatch
+on: push
 
 jobs:
   build:
@@ -32,8 +32,11 @@ jobs:
       - run: nohup npm run start-server &
 
       - name: Execute lambdatest cli
-        timeout-minutes: 5
-        run: npm run ci:lambdatest --build_name=${{ github.head_ref }}-${{ github.run_id }}
+        run: |
+          if npm run ci:lambdatest --build_name=${{ github.head_ref }}-${{ github.run_id }} != 0; then
+            echo "Test execution failed..."
+            exit 1
+          fi
         env:
           LT_USERNAME: ${{secrets.LT_USERNAME}}
           LT_ACCESS_KEY: ${{secrets.LT_ACCESS_KEY}}
