ss

diff --git a/.github/workflows/demo.yml b/.github/workflows/demo.yml
--- a/.github/workflows/demo.yml
+++ b/.github/workflows/demo.yml
@@ -7,5 +7,10 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - run: npm --version
-      - run: echo $?
+      - name: Execute lambdatest cli
+        run: |
+          if [ "npm --version" -ne "0" ]; then
+              echo "command failed"-$?
+          else
+              echo "command success"-$?
+          fi
